// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qandnswgyshjcysuslsw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFhbmRuc3dneXNoamN5c3VzbHN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyOTg2MjEsImV4cCI6MjA1Nzg3NDYyMX0.Sk4HLkJ5EexJ6Dkgl0gcrneljdFg1rgTL_ACMn5NClg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);